#include "mvk/SimpleGraphMvkOpHandler.h"

#include <cassert>

/*
 * DevNote: !!!ABOUT REVERTING OPERATION!!!
 * You only need to revert the operation on the graph
 * For instance: if add vertex failed, call _graph->removeVertex.
 * However, DON CALL the mapper remove function since a new operation is
 * generated by the 'removeVertex' and then, this operation is handled
 * here.
 * Note that, if the remove fails as well in MVK, this will call the addVertex
 * (Which already failed). This should not append except if the model is
 * NOT VALID at the very beginning. Here, we assume user work on model
 * that is valid at the beginning. (But we could improve this since it's
 * dangerous).
 */

SimpleGraphMvkOpHandler::SimpleGraphMvkOpHandler(const SimpleGraphMvkMapper* mapper, SimpleGraph* graph,
                                                 const std::string& model, const std::string& metamodel) {
    _mapperMVK = mapper;
    _graph = graph;
    _model = model;
    _metamodel = metamodel;
    assert(_mapperMVK != nullptr);
    assert(_graph != nullptr);
    assert(_model.size() > 1);
    assert(_metamodel.size() > 1);
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::VertexAddOperation& op) {
    bool success = _mapperMVK->vertexAdd(_model, _metamodel, op.getVertexID());
    if (!success) {
        _graph->removeVertex(op.getVertexID());
    }
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::VertexRemoveOperation& op) {
    bool success = _mapperMVK->vertexRemove(_model, _metamodel, op.getVertexID());
    if (!success) {
        _graph->addVertex(op.getVertexID());
    }
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::EdgeAddOperation& op) {
    bool success = _mapperMVK->edgeAdd(_model, _metamodel, op.getFromID(), op.getToID());
    if (!success) {
        _graph->removeEdge(op.getFromID(), op.getToID());
    }
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::EdgeRemoveOperation& op) {
    bool success = _mapperMVK->edgeRemove(_model, _metamodel, op.getFromID(), op.getToID());
    if (!success) {
        _graph->addEdge(op.getFromID(), op.getToID());
    }
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::AttributeAddOperation& op) {
    // Just some aliases for me
    const std::string& vertexID = op.getVertexID();
    const std::string& name = op.getAttributeName();
    const std::string& value = op.getAttributeValue();

    bool success = _mapperMVK->attributeAdd(_model, _metamodel, vertexID, name, value);
    if (!success) {
        _graph->removeAttribute(vertexID, name);
    }
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::AttributeRemoveOperation& op) {
    // Some aliases
    const std::string& vertexID = op.getVertexID();
    const std::string& name = op.getAttributeName();
    // TODO const std::string& value = op.getValue();

    bool success = _mapperMVK->attributeRemove(_model, _metamodel, vertexID, name);
    if (!success) {
        // TODO Get old value (Need to update this in AttributeRomveOperation)
        //_graph->setAttribute(vertexID, name, value);
    }
}

void SimpleGraphMvkOpHandler::handleOperation(const SimpleGraph::AttributeSetOperation& op) {
    // Some aliases
    const std::string& vertexID = op.getVertexID();
    const std::string& name = op.getAttributeName();
    const std::string& value = op.getAttributeValue();
    // TODO const std::string& oldvalue = op.getOldValue();

    bool success = _mapperMVK->attributeSet(_model, _metamodel, vertexID, name, value);
    if (!success) {
        // TODO Update collab-common to have old value
        //_graph->setAttribute(vertexID, name, oldvalue);
    }
}
